List genres = [{'genre': 'Sci-Fi Horror Films', 'netflixid': 1694},
  {'genre': 'Psychological Horror Films', 'netflixid': 4809},
  {'genre': 'B-Horror Films', 'netflixid': 8195},
  {'genre': 'Horror Films', 'netflixid': 8711},
  {'genre': 'Gory Horror Films', 'netflixid': 9509},
  {'genre': 'Japanese Horror Films', 'netflixid': 10750},
  {'genre': 'Cult Horror Films', 'netflixid': 10944},
  {'genre': 'Supernatural Horror Films', 'netflixid': 42023},
  {'genre': 'Deep Sea Horror Films', 'netflixid': 45028},
  {'genre': 'Classic Horror Films', 'netflixid': 48303},
  {'genre': 'Thai Horror Movies', 'netflixid': 65209},
  {'genre': 'Zombie Horror Films', 'netflixid': 75405},
  {'genre': 'Vampire Horror Films', 'netflixid': 75804},
  {'genre': 'Werewolf Horror Films', 'netflixid': 75930},
  {'genre': 'Horror Programmes', 'netflixid': 83059},
  {'genre': 'Horror Comedies', 'netflixid': 89585},
  {'genre': 'International Horror Movies', 'netflixid': 1475312},
  {'genre': 'Thriller & Horror Anime', 'netflixid': 1663282}];